### ISSUE TITLE
TODOs Report

### ISSUE THREAD

**Issue by KristofferNyvoll** [mathisfo/shower-post#28]
Architectural Document:

- [x] Oppdatere intro: Kristoffer
- [x] Skrive om Design Patterns - vent med dette til dette er kodet: Vemund
- [x] Fikse opp i modellene (views), skrive mer om de, og gjøre de mye større (newpages osv)
- [x] Fikse references: Vemund
- [x] Legge til en eller to kilder til
- [x] Lese over: Vemund

Requirements doc: 

- [x] Lese over hele: Kristoffer
- [x] Lese over hele: Vemund
- [x] Flytte tabeller opp i selve teksten: Kristoffer
- [x] Legge til bilde av hvordan den ferdige appen ser ut, er fint å ha et bilde rett etter den første figma-skissen
- [x] Fikse References: Vemund
- [x]  Poeng beregning må være konsistent

**Comment by vemund0507** [comment]
- [ ] Skrive om Observable pattern
